### PR TITLE
changed: assorted fixes

### PR DESCRIPTION
**Pull request by lovesegfault**
This fixes some small, mostly stylistic/cosmetic, issues I saw while navigating
the code.

- changed: sort cargo.toml
- changed: don't use 2015-style extern crate
- changed: don't use 2015-style #[macro_use]

### CODE REVIEW

**Comment by notgne2** [comment]
Cleanup has merged so this can be rebased/continued now

**Comment by lovesegfault** [comment]
> Cleanup has merged so this can be rebased/continued now

Done!

**Review by notgne2 — APPROVED** [review]
LGTM. Forgot to get to this sooner so it will need rebasing or merging again, sorry

**Comment by notgne2** [comment]
Oh apparently github has a magic button that works even though pushing to this branch doesn't, ok...

**Pull request merged**
