### PR TITLE
better error messages: provide node names

### LINKED ISSUE #273: output when deploying to multiple targets is unclear
When deploying to multiple hosts in one invocation using `--targets`, the log output of `deploy-rs` is unnecessarily unclear on which host an operation affects. This is especially confusing in case one of the deployments fails, but the others succeed, as there's no obvious indication *which* deploy failed, only that one of them did.

As an example, consider:
~~~
❯ deploy --targets .#chaski .#flora --dry-activate -s
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[chaski.system]
user = "root"
ssh_user = "root"
path = "/nix/store/6kj8i7d0yglnlkzpmxdn9ydz1l9l3hln-activatable-nixos-system-chaski-23.11.20240406.e38d7cb"
hostname = "chaski"
ssh_opts = []
[flora.system]
user = "root"
ssh_user = "root"
path = "/nix/store/j9wk9wy0v0xq2c0dgxh0diqvgna0wc3f-activatable-nixos-system-flora-23.11.20240406.e38d7cb"
hostname = "flora"
ssh_opts = []

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `chaski`
🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `flora`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `chaski`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `flora`
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix copy command resulted in a bad exit code: Some(1)
~~~

It'd be much nicer if the log messages would simply include the hostname again, so the last line would start with `🚀 ❌ [deploy to flora] [ERROR]` or something similar.

### PR DESCRIPTION
**Pull request by PhilTaken**
printing what node caused an error is very useful for debugging build or deployment failures, especially when deploying to several nodes at the same time

closes #273

### CODE REVIEW

**Comment by rvem** [comment]
Won't it make sense to include the node name into higher level error constructors (namely [`DeployProfile`](https://github.com/serokell/deploy-rs/blob/b3ea6f3/src/cli.rs#L384) and [`PushProfile`](https://github.com/serokell/deploy-rs/blob/b3ea6f3/src/cli.rs#L386)) and re-wrap them [here](https://github.com/serokell/deploy-rs/blob/b3ea6f3/src/cli.rs#L588) instead of updating `PushProfileError` constructors?

**Comment by PhilTaken** [comment]
Ah yes, that'd probably be a better option!

**Comment by PhilTaken** [comment]
I added the node name information to revokations as well, thought that might be just as useful

**Review by rvem — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
