### PR TITLE
[#210] Add activation script for darwin system and provide a usage example

### LINKED ISSUE #210: Deploying from macOS to macOS (nix-darwin)
It would be a good idea to support this scenario.

I have a nix-darwin config that I want to build _on_ the local mac, and deploy that _to_ a remote mac. That, or deploy _from_ the local mac letting it build remotely.

### PR DESCRIPTION
**Pull request by rvem**
Problem: It's possible to use 'deploy-rs' for deploying 'darwinSystem' configuration from 'nix-darwin' to a darwin system. However, there is no dedicated activatiot script for darwin and thus one has to come up with 'custom' activation script.

Solution:
1) Add 'darwin' attribute to 'lib.activate' that provides a script that
   should be used to activate 'darwinSystem' config with 'deploy-rs'.
2) Add a new 'examples/darwin' example that provides simple flake for
   deploying configuration to a darwin target.
   
Resolves #210

### CODE REVIEW

**Comment by PhilTaken** [comment]
Personally I wouldnt check the lockfile for an example into version control but apart from that it looks good. Can't test currently :/

**Comment by rvem** [comment]
> Personally I wouldnt check the lockfile for an example into version control

I didn't think about that previously by it indeed makes sense to not include it

**Comment by rvem** [comment]
@PhilTaken, will you get a chance to look at this PR once again? :sweat_smile:

**Comment by rvem** [comment]
From my side I can confirm that I already tested this on a VM and baremetal macOS instances

**Comment by PhilTaken** [comment]
@rvem I'll check it out this evening 😉 might even fire up a vm and try it out

**Review by PhilTaken — APPROVED** [review]

**Pull request merged**
